### ISSUE TITLE
s9s job  :  short option -G  for show job log is not handled.

### ISSUE THREAD

**Issue by freddielunchbird** [severalnines/s9s-tools#1]
s9s job --help
...
 -G, --log                  Show job log
...

How to repeat:

s9s job   --controller=localhost:9500 --job-id=79  -G
s9s: invalid option -- 'G'
Error in command line options.

Whereas

s9s job   --controller=localhost:9500 --job-id=79  --log 

prints out the expected job messages

**Comment by lpere** [comment]
I think I managed to fix this.

**Comment by freddielunchbird** [comment]
no, did not work.
You added your change under "readOptionsCluster", but it should have been under readOptionsJob and also the 'G' was not added to getopt. 

Thanks
johan
