### ISSUE TITLE
cmon creating defunct processes

### ISSUE THREAD

**Issue by vivek-deep** [severalnines/s9s-tools#3]
CMON process creates a number of defunct processes which takes up a lot of CPU and effectively hangs until restarted. Then it sends out a lod of emails which are not relevant currently

**Comment by lpere** [comment]
Could you please provide some more information? What emails do you get?

And sorry about the delay, people usually are not posting controller issues here, the cmon controller has its own error reporting forums. But that's ok, I am the developer in that team too, so I can work on this if you give me some more information.

**Comment by kedazo** [comment]
Closing this old (and unrelated to s9s CLI itself) ticket
