### ISSUE TITLE
Allow to create backups without specifying a hostname

### ISSUE THREAD

**Issue by freddielunchbird** [severalnines/s9s-tools#4]
Hi,
it must be possible to take backups without specifying:
  --nodes=NODELIST           The list of nodes involved in the backup.

In that case, it is cmon that will auto-select the node to backup .

Thus, i would like to be able to create a backup like. i.e, omitting --node/--nodes as an argument:

s9s backup --create --cluster-id=1  --backup-method=mariabackupfull  --parallellism=2 --on-node  

BR
johan

**Comment by lpere** [comment]
Fixed, thanks!
